### ISSUE TITLE
리뷰 저장 시 백엔드에서 생성된 user_id를 프론트로 가져오는 방법 문의 드립니다. 

### ISSUE THREAD

**Issue by ssook1222** [visionWWW/Mimi#3]
<img width="280" alt="스크린샷 2021-11-05 오전 12 38 20" src="https://user-images.githubusercontent.com/60427387/140367818-c648cc80-45a7-4758-8fa5-e084477f37cf.png">
지금 테이블의 상태가 위 이미지랑 같은 상황입니다.
user login으로 아래 이미지처럼 닉네임과 비밀번호를 받고 리뷰 쓰기로 넘어가게끔 만들고 나서,
<img width="734" alt="스크린샷 2021-11-05 오전 12 39 04" src="https://user-images.githubusercontent.com/60427387/140368019-f64f0021-e8d0-4655-b67b-fc4bdda85d1e.png">
review table의 foreign key인 user_id를 받아서 리뷰 폼에 있는 데이터들과 함께 리뷰 테이블에 저장하고자 합니다.
그런데 user_id는 닉네임/비밀번호를 입력하는 페이지에서 auto_increment로 백엔드에서 생성되다 보니까 해당 데이터(user_id)를 저 리뷰 작성하는 페이지에서 어떻게 받아와야 할 지 모르겠습니다.      
<img width="1091" alt="스크린샷 2021-11-05 오전 12 39 10" src="https://user-images.githubusercontent.com/60427387/140368745-77a8d030-b0ac-4d10-8015-1cf1fd5d6761.png">

다시 말하자면, 백엔드에서 생긴 user_id를 review 작성 페이지로 불러오고 싶습니다.

**Comment by eastflag** [comment]
이거를 해결할려면 회원가입 페이지와 로그인 페이지를 구현해야 되.
password와 nickname으로 회원가입을 하면 서버에서 user_id가 자동으로 생성되고,
로그인을 성공하면 생성된 user_id를 가져다가 쓰도록.

로그인 안한 상태에서 리뷰를 쓸려고 하면 로그인 페이지로 팅겨내야 하고.
원래는 로그인을 성공하면 서버에서 jwt 토큰을 생성해서 넘겨줘야 하는데 이게 어렵다면 서버에서 그냥 user_id만이라도 리턴해두고,
클라이언트는 넘어온 user_id를 localStorage에 저장해서 가져다 쓰면되.



2021년 11월 5일 (금) 오전 12:47, ssook ***@***.***>님이 작성:

**Comment by ssook1222** [comment]
해결했습니다 : ) 감사합니다!
